### PR TITLE
CMake updates for NastranIO/pyNastran/Cython.

### PR DESCRIPTION
**Pull request by jdeaton**
NastranIO integrated as an optional unit into MAST library via CMake completed.

### CODE REVIEW

**Comment by jdeaton** [comment]
@JohnDN90 its been awhile since I ran Cython. Which of the source files in what you did was generated by cython? I think we should setup CMake to run Cython during configuration rather than committing the final version in the repo.

**Comment by JohnDN90** [comment]
[This](https://github.com/MASTmultiphysics/mast-multiphysics/blob/nastran_io-cmake/src/mesh/pynastranIO.pyx) file generates the pynastranIO.h and pynastranIO.cpp files after running cythonize on it.  I agree that in the end we should have CMake cythonize the .pyx and generate the other two files, I just wanted to include them in the initial commit until we get CMake running cythonize.

The NastranIO.cpp and NastranIO.h are manually created by me.

**Comment by jdeaton** [comment]
> [This](https://github.com/MASTmultiphysics/mast-multiphysics/blob/nastran_io-cmake/src/mesh/pynastranIO.pyx) file generates the pynastranIO.h and pynastranIO.cpp files after running cythonize on it. I agree that in the end we should have CMake cythonize the .pyx and generate the other two files, I just wanted to include them in the initial commit until we get CMake running cythonize.
> 
> The NastranIO.cpp and NastranIO.h are manually created by me.

Just curious, did you have trouble when compiling MAST using the `pynastranIO.h/.cpp` files you generated needing headers for numpy? When I compile your files, it looks like they have `#include "numpy/arrayobject.h"` and `#include "numpy/ufuncobject.h"` in them, which I'm not currently including in the MAST `target_include_directories()`. Are your Python modules on a standard path or something?

I believe I need to somehow automatically find the path to these numpy headers and be able to feed them to the MAST compilation.

**Comment by jdeaton** [comment]
Just answered my last comment. You were using the built-in CMake FindPython3, which finds the Numpy header path and includes it with the regular Python header variable. I replaced it with a custom FindPython3 since the built-in was having trouble with my Spack build.

**Pull request merged**
